# Generated by Django 2.2.14 on 2020-12-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ManyToManyField(blank=True, related_name='Publicacion', to='comentarios.Comentario')),
                ('tags', models.ManyToManyField(blank=True, related_name='Publicacion', to='tags.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publicacion', to='usuarios.User')),
            ],
        ),
    ]
