# Generated by Django 2.2.14 on 2020-12-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['content']},
        ),
    ]
